#conexion a mysql

# URL: Cambia 'postgresql' por 'mysql', el puerto al 3306, y pon el nombre de tu base de datos
spring.datasource.url=jdbc:mysql://localhost:3306/recursos_humanos_db?useSSL=false&serverTimezone=UTC

# El usuario por defecto de XAMPP siempre es root
spring.datasource.username=root

# Por defecto, en XAMPP la contraseña de root viene VACÍA (no pongas nada después del =)
spring.datasource.password=

# El driver cambia para ser compatible con MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Opcional: Esto ayuda a que Spring Boot cree las tablas automáticamente en MySQL si no existen
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
